const config = {
  target: "Mitch O'Farrell",
  total_cash: 650274,
  candidate: 'Hugo Soto-Martinez',
  district: 'CD13',
  candidate_pronoun: 'him',
  candidate_pronoun2: 'he',
  candidate_bio:
    "Hugo Soto-Martinez is a corporate-free, democratic socialist candidate running against Mitch O'Farrell in CD13. If we tell you Hugo promises to do good things that will help people, you can always say, “Well, so does Mitch, pal!” And Mitch does promise a lot. However, Hugo has the track-record and forward-thinking bona fides to back up his progressive promises. As a teenager, Hugo began working in a non-union hotel after his father became disabled, and seven years later helped organize the first union at that hotel. This led him to become an organizer for UNITE HERE (the union that covers everyone from hospitality industry workers to folks in food service, gaming, airports and more), where he’s worked for the last decade and a half. That’s why we support Hugo. Because he’s spent over half his life helping to win material gains for workers, immigrants, the unhoused, people of color, and everyone else that’s been crushed by the exploitation of profit-driven economic life. \n\n Hugo doesn’t take money from cops, private developers, fossil fuel companies or lobbyists, and is instead funded by the people. Hugo has the most in district donations of any candidate in his race, with an average donation of $57 dollars. In fact, 80% of Hugo’s donations are $50 or less!",
  target_bio:
    "It’s not personal. If we passed Mitch on the street and he had a flat tire, we’d probably help him out. Or at least call AAA. But we’re “picking” on Mitch because he is a bog-standard example of a lackluster Los Angeles City Council member. He says plenty of nice, surface level things, but his actions are awful and regressive and end up hurting large swaths of Angelenos. \n\n Politicians like Mitch purport to be high-minded progressives, but through laziness, malice, greed, ignorance or some combination thereof, hurt the people they say they’re protecting, and have made this city nearly unliveable. And this is Mitch in a nutshell. \n\n He claims to be “recognized as a leader in the production and protection of affordable housing”, all while hoovering up giant sums of cash from real estate developers that drive up rent and push the working folks living in CD13 further and further away. \n\n Mitch claims to have “worked with state and county partners to bring billions of dollars in funding to address the City’s homelessness crisis.” Yet his heavy-handed police-state tactics in Echo Park Lake, despite his claims, led to as many deaths among the former residents as people in permanent housing, with dozens more missing and unaccounted for, according to a UCLA studyxxz. It’s maddening because while other city council members have worked toward successful housing projects that Mitch could have implemented as well, he opted for showy violence. \n\n In Mitch’s role as councilmember, he’s done more to hurt the people of CD13 than help, and this website is here to show you exactly how. Usually city council races are a real race to the bottom affair, but this time you actually have an alternative! Hugo Soto-Martinez is a corporate-free, democratic socialist candidate running against Mitch O'Farrell in CD13."
}
config.target_first = config.target.split(' ')[0]
config.candidate_first = config.candidate.split(' ')[0]
export default config
